Models/Turnos.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Proyecto_1.Models
{
    public class Turnos
    {
        public int idTurno { get; set; }
        public int idCurso { get; set; }

        [System.ComponentModel.DisplayName("Cantidad max de alumnos:")]
        public int Alumnos { get; set; }

        [Required]
        [System.ComponentModel.DisplayName("Dia:")]
        public string Dia { get; set; }

        [Required]
        [System.ComponentModel.DisplayName("Hora Inicio:")]
        [RegularExpression("^[0-9:]{1,5}$", ErrorMessage = "Solo se admiten numeros y un separador para minutos de 2 puntos. Ej: 14:30")]
        [StringLength(5, MinimumLength = 1, ErrorMessage = "Debe tener al menos un numero y maximo 4")]
        public string Inicio { get; set; }           //Inicio es la hora de comienzo del turno

        [Required]
        [System.ComponentModel.DisplayName("Hora Fin:")]
        [RegularExpression("^[0-9:]{1,5}$", ErrorMessage = "Solo se admiten numeros y un separador de 2 puntos. Ej: 9:15")]
        [StringLength(5, MinimumLength = 1, ErrorMessage = "Debe tener al menos un numero y maximo 4")]
        public string Fin { get; set; }

        [System.ComponentModel.DisplayName("Fecha inicio de clase:"),
         DisplayFormat(DataFormatString = "{0:dd/MM/yy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.DateTime)]
        [Required]
        public string s_FechaInicio { get; set; }

        [System.ComponentModel.DisplayName("Fecha inicio de clase:"),
         DisplayFormat(DataFormatString = "{0:dd/MM/yy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.DateTime)]
        [Required]
        public DateTime FechaInicio { get; set; }

        public Turnos()
        { }

        public Turnos(int idT, int idC, String Day, DateTime FI, String sFI, String inicio, String fin, int alumnos)
        {
            idTurno = idT;
            idCurso = idC;
            Dia = Day;
            FechaInicio = FI.Date;
            s_FechaInicio = sFI;
            Inicio = inicio;
            Fin = fin;
            Alumnos = alumnos;
        }

        public Turnos(int idC, String Day, DateTime FI, String inicio, String fin, int alumnos)
        {
            idCurso = idC;
            Dia = Day;
            FechaInicio = FI;
            Inicio = inicio;
            Fin = fin;
            Alumnos = alumnos;
        }
    }
}

ViewModels/Caja.cs
using System;

namespace Proyecto_1.ViewModels
{
    public class Caja
    {
        public String Concepto { get; set; }
        public string Concepto2 { get; set; }
        public DateTime Fecha { set; get; }

        public Decimal Monto { get; set; }

        public string Usuario { get; set; }

        public Caja()
        { }

        public Caja(string concepto, DateTime fecha, decimal monto, string usuario, string concepto2)
        {
            Concepto2 = concepto2;
            Concepto = concepto;
            Fecha = fecha;
            Monto = monto;
            Usuario = usuario;
        }

    }
}

Controllers/TurnosController.cs
using System;
using System.Web.Mvc;
using Proyecto_1.Models;
using System.Linq;
using Proyecto_1.ViewModels;
using System.Collections.Generic;
using System.Data.SqlClient;
using AtelierChef1.ViewModels;
using System.Web.Configuration;

namespace Proyecto_1.Controllers
{
    public class TurnosController : Controller
    {
        private static String _mensajeExito;
        private static String _mensajeError;
        private static int _idCurso;
        private static int _idTurno;
        private static int _idClase;
        public static int _idAlumno;
        private static String _nombreCurso;
        private static String _nombreTurno;
        private static String _fechaTurno;
        private static string _horaInicioTurno;
        private static string _horaFinTurno;
        private static string _fechaClase;
        private static DateTime _fechaClaseDateTime;
        private static string _horaInicioClase;
        private static string _horaFinClase;
        private static IList<Alumno> _lista2;
        private static Decimal _total;
        private static string _mensaje;
        private static int _control;
        private static int _control2 = 0;
        private static string _cultura = WebConfigurationManager.AppSettings["cultura"]; //COMENTARIO22222


        public ActionResult Index()
        {
            return View();
        }
        public void setMensaje(string mensaje)
        {
            _mensajeExito = mensaje;
        }

        public ActionResult prueba(string cantidad, string precio, string idProducto)
        {
            var x = precio;
            return View();
        }

        // recibe id y nombre del curso del cual se muestran los turnos
        public ActionResult Turno(int id, String Nombre)
        {
            try
            {
                _idCurso = id;
                _nombreCurso = Nombre;
                TurnosHandle th = new TurnosHandle();
                ModelState.Clear();

                if (_mensajeExito != null)
                {
                    ViewBag.mensajeExito = _mensajeExito;
                }

                if (_mensajeError != null)
                {
                    ViewBag.mensajeError = _mensajeError;
                }

                _control = 1;
                _mensajeExito = "";
                _mensajeError = "";
                ViewBag.nombreCurso = Nombre;
                ViewBag.control2 = 0;
                return View(th.ListarTurnosDeUnCurso(id));
            }
            catch (Exception e)
            {
                CursosController cc = new CursosController();
                cc.SetMensajeError(e.Message);
                return RedirectToAction("Curso", "Cursos");
            }
        }

        //Este action se lo usa cuando se hace click en el boton "guardar" de la vista "CrearTurno" para retornar a la vista "Turno" (primero pasa por el action "agregar" que es quien lo llama)
        //Difiere del action anterior en que no recibe parametros, puesto q estos ya estan guardados en variables estaticas.
        public ActionResult Turno2()
        {
            TurnosHandle th = new TurnosHandle();
            ModelState.Clear();

            if (_mensajeExito != null)
            {
                ViewBag.mensajeExito = _mensajeExito;
            }

            if (_mensajeError != null)
            {
                ViewBag.mensajeError = _mensajeError;
            }

            _mensajeExito = "";
            _mensajeError = "";
            ViewBag.nombreCurso = _nombreCurso;
            ViewBag.control2 = 0;
            return View("Turno", th.ListarTurnosDeUnCurso(_idCurso));
        }

        //Este action se lo usa al hacer click en el checkbox de la vista turno, para listar todos los turnos.
        public ActionResult Turno3()
        {
            TurnosHandle th = new TurnosHandle();
            ModelState.Clear();

            if (_mensajeExito != null)
            {
                ViewBag.mensajeExito = _mensajeExito;
            }

            if (_mensajeError != null)
            {
                ViewBag.mensajeError = _mensajeError;
            }

            _mensajeExito = "";
            _mensajeError = "";
            ViewBag.nombreCurso = _nombreCurso;

            ViewBag.control2 = 1;
            return View("Turno", th.ListarTurnosDeUnCursoSinRestriccion(_idCurso));
        }

        public ActionResult CrearTurno()
        {
            ViewBag.nombre = _nombreCurso;
            return View("CrearTurno");
        }

        public ActionResult CrearClases()
        {
            if (_mensajeExito != null)
            {
                ViewBag.mensajeExito = _mensajeExito;
            }

            if (_mensajeError != null)
            {
                ViewBag.mensajeError = _mensajeError;
            }
            CursosHandle cuh = new CursosHandle();
            TurnosHandle th = new TurnosHandle();
            ClasesHandle ch = new ClasesHandle();
            try
            {
                RecetasHandle rh = new RecetasHandle();
                ViewBag.listaRecetas = rh.ListarRecetas();
                ViewBag.listaAlumnos = th.AlumnosInscriptos2(_idTurno, _idCurso);
            }
            catch (Exception e)
            {
                _mensajeError = e.Message;
            }

            ViewBag.idturno = _idTurno;
            ViewBag.fecha = _fechaTurno;
            ViewBag.nombreCurso = _nombreCurso;
            ViewBag.nombreTurno = _nombreTurno;
            ViewBag.mensajeExito = _mensajeExito;
            ViewBag.mensajeError = _mensajeError;

            _mensajeError = "";
            _mensajeExito = "";

            List<ClasesConRecetas> ListaClasesConRecetas = new List<ClasesConRecetas>();
            var ListaClasesDeUnTurno = ch.ListarClasesDeUnTurno(_idTurno);
            var ListaRecetasDeUnTurno = ch.ListarRecetasDeTurno(_idTurno);

            foreach (var item in ListaClasesDeUnTurno)
            {
                var ccr = new ClasesConRecetas(item.idClase, item.idCurso, item.FechaInicio, item.FechaFin, item.Descripcion);
                ListaClasesConRecetas.Add(ccr);
            }

            var i = 0;
            var nombres = "";
            foreach (var item in ListaRecetasDeUnTurno)
            {
                if (i == item.idClase)
                {
                    nombres = nombres + " - " + item.Nombre;
                    ListaClasesConRecetas.Find(x => x.idClase == item.idClase).receta = nombres;
                }
                else
                {
                    ListaClasesConRecetas.Find(x => x.idClase == item.idClase).receta = item.Nombre;
                    nombres = item.Nombre;
                }
                i = item.idClase;
            }

            return View("CrearClases", ListaClasesConRecetas);
        }

        public ActionResult CrearClases2(string id) //recibe idTurno y manda la vista para la creacion de las clases  y donde se listan todas las clases y alumnos. vista despues del calendario.
        {
            _idTurno = Convert.ToInt32(id);
            CursosHandle cuh = new CursosHandle();
            TurnosHandle th = new TurnosHandle();
            if (_idCurso == 0)
            {
                _idCurso = th.TraeridCurso(_idTurno).FirstOrDefault().idCurso;
            }
            var t1 = th.ListarTurnosDeUnCursoSinRestriccion(_idCurso).Find(y => y.idTurno == _idTurno);
            _nombreTurno = t1.Dia.ToUpper() + " de " + t1.Inicio + " a " + t1.Fin;

            ClasesHandle ch = new ClasesHandle();
            try
            {
                _fechaTurno = ch.ListarClasesDeUnTurno(_idTurno).Max(t => t.FechaInicio).AddDays(7).ToString("dd/MM/yyyy");
            }
            catch (Exception e)
            {
                _fechaTurno = t1.FechaInicio.ToString("dd/MM/yyyy");
            }

            try
            {
                RecetasHandle rh = new RecetasHandle();
                ViewBag.listaRecetas = rh.ListarRecetas();
            }
            catch (Exception e)
            {
                _mensajeError = e.Message;
            }

            ViewBag.idTurno = _idTurno;
            ViewBag.fecha = _fechaTurno;
            ViewBag.nombreCurso = _nombreCurso;
            ViewBag.nombreTurno = _nombreTurno;
            ViewBag.idCurso = _idCurso;
            ViewBag.mensajeExito = _mensajeExito;
            ViewBag.mensajeError = _mensajeError;
            _mensajeError = "";
            _mensajeExito = "";

            List<ClasesConRecetas> ListaClasesConRecetas = new List<ClasesConRecetas>();
            var ListaClasesDeUnTurno = ch.ListarClasesDeUnTurno(_idTurno);
            var ListaRecetasDeUnTurno = ch.ListarRecetasDeTurno(_idTurno);

            foreach (var item in ListaClasesDeUnTurno)
            {
                var ccr = new ClasesConRecetas(item.idClase, item.idCurso, item.FechaInicio, item.FechaFin, item.Descripcion, item.idTurno);
                ListaClasesConRecetas.Add(ccr);
            }

            var i = 0;
            var nombres = "";
            foreach (var item in ListaRecetasDeUnTurno)
            {
                if (i == item.idClase)
                {
                    nombres = nombres + " - " + item.Nombre;
                    ListaClasesConRecetas.Find(x => x.idClase == item.idClase).receta = nombres;
                }
                else
                {
                    ListaClasesConRecetas.Find(x => x.idClase == item.idClase).receta = item.Nombre;
                    nombres = item.Nombre;
                }

                i = item.idClase;
            }
            //var costo = cuh.TraerCostoCurso(_idCurso).FirstOrDefault().Costo;
            //var sumaPago = th.DetallePagoAlumno(_idTurno, id).Sum(x => x.Monto);
            //var Adeuda = costo - sumaPago;

            //ViewBag.deuda = Adeuda;
            ViewBag.control = _control;
            ViewBag.listaAlumnos = th.AlumnosInscriptos2(_idTurno, _idCurso);

Views/Turnos/AlumnosInscriptos.cshtml
@model IEnumerable<Proyecto_1.Models.Alumno>

@{
    ViewBag.Title = "Alumnos inscriptos";
}

<head>
    <script src="~/Content/sweetalert-master/dist/sweetalert.min.js"> </script>
    <link rel="stylesheet" type="text/css" href="~/Content/sweetalert-master/dist/sweetalert.css">
    <link rel="stylesheet" href="~/Content/jquery-ui-1.12.1.custom/jquery-ui.css" />
</head>

<div class="container-fluid" style="padding: 0% 5% 5% 5%">

    @if (ViewBag.mensajeExito != null)
    {
        <div class="alert alert-success" role="alert">
            <strong style="color:green">@ViewBag.mensajeExito</strong>
        </div>
    }
   
    @if (ViewBag.mensajeError != null)
    {
        <div class="alert alert-warning" role="alert">
            <strong style="color:orangered">@ViewBag.mensajeError</strong>
        </div>
    }
   
    <h4 style="margin-top: 15px; margin-bottom:20px; margin-left: 6px; color: black; font-size:medium">Alumnos inscriptos en el turno: <b style="color:forestgreen"> @ViewBag.nombreTurno </b> del curso <b style="color:forestgreen; text-transform:uppercase"> @ViewBag.nombreCurso </b></h4>
    
    <table class="table table-striped table-hover table-bordered">
        <tr style="background-color:cadetblue">
            <th>Alumno</th>
            <th>Acciones</th>
        </tr>
        @foreach (var item in Model)
            {
            <tr>
                <td>@item.Apellido  @item.Nombre</td>
                <td>
                    <input type="button" value="Pagos" class="btn btn-primary" style="padding:5px 10px; font-size:small" onclick="location.href='@Url.Action("VerDetalle", "Turnos", new {id= item.idAlumno, nombre= item.Nombre, apellido= item.Apellido})'" />
                </td>
            </tr>
        }
    </table>

    <input type="button" value="Volver" class="btn btn-warning" onclick="location.href='@Url.Action("Turno","Turnos", new { id= ViewBag.idCurso, Nombre= ViewBag.nombreCurso})'" />

</div>

Views/Turnos/Caja.cshtml
@model IEnumerable<Proyecto_1.ViewModels.Caja>

@{
    ViewBag.Title = "Caja";
}
<head>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Content/bootstrap-daterangepicker-master/moment.min.js"></script>

    <script src="~/Content/bootstrap-daterangepicker-master/daterangepicker.js"></script>
    <link href="~/Content/bootstrap-daterangepicker-master/daterangepicker.css" rel="stylesheet" />

    <script type="text/javascript">
        $(function () {
            $('input[name="fecha"]').daterangepicker(
             {
                 autoUpdateInput: false,
                 opens: 'right',
                 drops: 'down',
                 autoApply: true,
                 //singleDatePicker: true,
                 //showDropdowns: true,
                 locale: {

                     format: 'DD/MM/YYYY',
                     "separator": "-",
                     "applyLabel": "Apply",
                     "cancelLabel": "Cancel",
                     "fromLabel": "Desde",
                     "toLabel": "Hasta",
                     "customRangeLabel": "Custom",
                     "weekLabel": "W",
                     "daysOfWeek": [
                     "Dom",
                     "Lun",
                     "Mar",
                     "Mie",
                     "Jue",
                     "Vie",
                     "Sab"
                     ],
                     "monthNames": [
                     "Enero",
                     "Febrero",
                     "Marzo",
                     "Abril",
                     "Mayo",
                     "Junio",
                     "Julio",
                     "Agosto",
                     "Septiembre",
                     "Octubre",
                     "Noviembre",
                     "Diciembre"
                     ],
                     "firstDay": 1
                 },
                 //startDate: new Date,
                 // endDate: new Date
             });

            $('input[name="fecha"]').on('apply.daterangepicker', function (ev, picker) {
                $(this).val(picker.startDate.format('DD/MM/YYYY') + ' - ' + picker.endDate.format('DD/MM/YYYY'));
            });

            $('input[name="fecha"]').on('cancel.daterangepicker', function (ev, picker) {
                $(this).val('');
            });
        });
    </script>
</head>

<div class="container-fluid" style="padding: 0% 5% 5% 5%">

    @if (ViewBag.mensajeExito != null)
    {
        <div class="alert-success" role="alert">
            <strong style="color:green">@ViewBag.mensajeExito</strong>
        </div>
    }

    @if (ViewBag.mensajeError != null)
    {
        <div class="alert-warning" role="alert">
            <strong style="color:orangered">@ViewBag.mensajeError</strong>
        </div>
    }

    <div class="row" style="margin-right:5px">
            <ul class="ui-corner-right" style="font-size:medium; list-style-type:square; float:right">
                <li style="color:#ffaf4b">Gastos: $@ViewBag.totalGastos</li>
                <li style="color:cornflowerblue">Ventas bazar: $@ViewBag.TotalVentas </li>
                <li style="color:darkseagreen">Ingresos cursos: $@ViewBag.totalPagos</li>
                <li style="color:darkgreen">Total bruto: $@ViewBag.total</li>
            </ul>

        <fieldset>
            <form action='@Url.Action("Caja2","Turnos")' style="margin-left:0px; margin-bottom:0px">
                <div class="form-inline">
                    <div class="form-group">
                        <label class="control-label" for="fecha">Filtrar por mes:</label>
                        <input type="text" id="fecha" class="form-control" style="margin-right:5px; width:190px" name="fecha" required />
                        <input type="submit" class="btn btn-primary" value="Filtrar" />
                        <input type="button" value="Descargar" class="btn btn-default" onclick="location.href='@Url.Action("GenerarExcel","Turnos")'" />
                    </div>
                </div>
            </form>
        </fieldset>
    </div>

    <div style="margin-bottom:10px">
        <h3 style="margin-top:5px; margin-bottom:5px">@ViewBag.mensaje</h3>
    </div>

    <table style="margin-top:5px" class="table table-hover table-bordered">
        <tr style="background-color:cadetblue">
            <th>Fecha</th>
            <th>Concepto </th>
            <th>Monto</th>
        </tr>

        @foreach (var item in Model)
            {
                if (item.Concepto == "Cuota" || item.Concepto == "Inscripcion")
                {
                <tr style="background-color:#D5F5E3">
                    <td>@item.Fecha.ToString("dd/MM/yyyy")</td>
                    <td> @item.Concepto</td>
                    <td>$@item.Monto</td>
                </tr>
            }

            else
            {
                if (item.Concepto == "Venta bazar")
                {
                    <tr style="background-color:cornflowerblue">
                        <td>@item.Fecha.ToString("dd/MM/yyyy")</td>
                        <td> @item.Concepto</td>
                        <td>$@item.Monto</td>
                    </tr>
                }
                else
                {
                    if (item.Concepto == "Compra Bazar")
                    {
                        <tr style="background-color:burlywood">
                            <td>@item.Fecha.ToString("dd/MM/yyyy")</td>
                            <td> @item.Concepto</td>
                            <td>$@item.Monto</td>
                        </tr>
                    }
                    else
                    {
                        <tr style="background-color:#ffaf4b">
                            <td>@item.Fecha.ToString("dd/MM/yyyy")</td>
                            <td> @item.Concepto</td>
                            <td>$@item.Monto</td>
                        </tr>
                    }
                }
            }
        }
    </table>
</div>

Views/Turnos/CrearTurno.cshtml
@model Proyecto_1.Models.Turnos

@{
    ViewBag.Title = "Crear Turno";
}
<head>
        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Content/bootstrap-daterangepicker-master/moment.min.js"></script>
        @*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@
        <script src="~/Content/bootstrap-daterangepicker-master/daterangepicker.js"></script>
        <link href="~/Content/bootstrap-daterangepicker-master/daterangepicker.css" rel="stylesheet" />

        <script type="text/javascript">
        $(function () {
            $('input[name="s_FechaInicio"]').daterangepicker(
                {
                    singleDatePicker: true,
                    showDropdowns: true,
                    autoUpdateInput: false,
                    locale: {
                        format: 'DD/MM/YYYY',
                        "separator": "-",
                        "applyLabel": "Apply",
                        "cancelLabel": "Cancel",
                        "fromLabel": "Desde",
                        "toLabel": "Hasta",
                        "customRangeLabel": "Custom",
                        "weekLabel": "W",
                        "daysOfWeek": [
                        "Dom",
                        "Lun",
                        "Mar",
                        "Mie",
                        "Jue",
                        "Vie",
                        "Sab"
                        ],
                        "monthNames": [
                        "Enero",
                        "Febrero",
                        "Marzo",
                        "Abril",
                        "Mayo",
                        "Junio",
                        "Julio",
                        "Agosto",
                        "Septiembre",
                        "Octubre",
                        "Noviembre",
                        "Diciembre"
                        ],
                        "firstDay": 1
                    },
                    startDate: new Date,
                    endDate: new Date
                });

            $('input[name="s_FechaInicio"]').on('apply.daterangepicker', function (ev, picker) {
                $(this).val(picker.startDate.format('DD/MM/YYYY'));
            });

            $('input[name="s_FechaInicio"]').on('cancel.daterangepicker', function (ev, picker) {
                $(this).val('');
            });
        });
        </script>
    </head>
<div class="container-fluid" style="padding: 0% 5% 5% 5%">

    @if (ViewBag.mensajeError != null)
    {
        <div class="alert alert-warning" role="alert">
            <strong style="color:orangered; margin-left:100px">@ViewBag.mensajeError</strong>
        </div>
    }

    <form class="form-horizontal" method="post" action="@Url.Action("AgregarTurnoNuevo","Turnos")">
        <fieldset style="padding:0% 5% 5% 5% ">
            <legend style="margin-top:5px; margin-bottom:2px; margin-left:5px; color:black">Nuevo turno para el curso: <b style="color:forestgreen; text-transform:uppercase"> @ViewBag.nombre </b></legend>
            <label style="font-size:small; margin-top:10px">(*) Campos obligatorios</label>
            <div class="form-group" style="margin-top:0px">
                <label for="s_FechaInicio" class="control-label">Fecha Inicio (*)</label>
                <div>
                    <input type="text" name="s_FechaInicio" style="max-width:250px" class="form-control" id="s_FechaInicio" placeholder="dd/mm/yyyy" required value="">
                </div>
            </div>

            <div class="form-group">
                <label for="select" class="control-label">Hora Inicio (*)</label>
                <div>
                    <select class="form-control" style="max-width:250px" name="Inicio" id="select" required>
                        <option value="" disabled selected>Hora Inicio</option>
                        <option value="08:00">08:00</option>
                        <option value="08:30">08:30</option>
                        <option value="09:00">09:00</option>
                        <option value="09:30">09:30</option>
                        <option value="10:00">10:00</option>
                        <option value="10:30">10:30</option>
                        <option value="11:00">11:00</option>
                        <option value="11:30">11:30</option>
                        <option value="12:00">12:00</option>
                        <option value="12:30">12:30</option>
                        <option value="13:00">13:00</option>
                        <option value="13:30">13:30</option>
                        <option value="14:00">14:00</option>
                        <option value="14:30">14:30</option>
                        <option value="15:00">15:00</option>
                        <option value="15:30">15:30</option>
                        <option value="16:00">16:00</option>
                        <option value="16:30">16:30</option>
                        <option value="17:00">17:00</option>
                        <option value="17:30">17:30</option>
                        <option value="18:00">18:00</option>
                        <option value="18:30">18:30</option>
                        <option value="19:00">19:00</option>
                        <option value="19:30">19:30</option>
                        <option value="20:00">20:00</option>
                        <option value="20:30">20:30</option>
                        <option value="21:00">21:00</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="select" class="control-label">Hora Fin (*)</label>
                <div>
                    <select class="form-control" style="max-width:250px" name="Fin" id="select" required>
                        <option value="" disabled selected>Hora Fin</option>
                        <option value="10:00">10:00</option>
                        <option value="10:30">10:30</option>
                        <option value="11:00">11:00</option>
                        <option value="11:30">11:30</option>
                        <option value="12:00">12:00</option>
                        <option value="12:30">12:30</option>
                        <option value="13:00">13:00</option>
                        <option value="13:30">13:30</option>
                        <option value="14:00">14:00</option>
                        <option value="14:30">14:30</option>
                        <option value="15:00">15:00</option>
                        <option value="15:30">15:30</option>
                        <option value="16:00">16:00</option>
                        <option value="16:30">16:30</option>
                        <option value="17:00">17:00</option>
                        <option value="17:30">17:30</option>
                        <option value="18:00">18:00</option>
                        <option value="18:30">18:30</option>
                        <option value="19:00">19:00</option>
                        <option value="19:30">19:30</option>
                        <option value="20:00">20:00</option>
                        <option value="20:30">20:30</option>
                        <option value="21:00">21:00</option>
                        <option value="21:30">21:30</option>
                        <option value="22:00">22:00</option>
                        <option value="22:30">22:30</option>
                        <option value="23:00">23:00</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="Alumnos" class="control-label">Cantidad de Alumnos</label>
                <div>
                    <input type="text" name="Alumnos" style="max-width:250px" class="form-control" id="Alumnos" value="10" required>
                </div>
            </div>

            <div class="form-group">
                <label for="select" class="control-label">Clases (*)</label>
                <div>
                    <select class="form-control" style="max-width:250px" name="cantidadClases" id="select" required>
                        <option value="" disabled selected>Cantidad de clases</option>
                        <option value=1>1</option>
                        <option value=2>2</option>
                        <option value=3>3</option>
                        <option value=4>4</option>
                        <option value=5>5</option>
                        <option value=6>6</option>
                        <option value=7>7</option>
                        <option value=8>8</option>
                        <option value=9>9</option>
                        <option value=10>10</option>
                        <option value=11>11</option>
                        <option value=12>12</option>
                    </select>
                </div>
            </div>

            <div class="form-check">
                <label class="form-check-label">
                    <input class="form-check-input" name="autocompletado" value="true" type="checkbox" checked>
                    Autocompletar clases. <br />
                    Si esta opción esta activada, las clases se crearan por defecto con la descripción y recetas asociadas del último turno que se haya creado para este curso. <br />
                    <label style="color:darkred">Nota: El autocompletado solo tendrá efecto, si la cantidad de clases indicada coincide con la del último turno que se haya creado.</label>
                </label>
            </div>

            <div class="form-group">
                <div style="margin-top:8px">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                    <input type="button" value="Cancelar" class="btn btn-warning" onclick="location.href='@Url.Action("Turno2", "Turnos")'" />
                </div>
            </div>
        </fieldset>
    </form>
    </div>